//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS2018WFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordini
    {
        public int PK_UID { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> codice { get; set; }
        public string descr { get; set; }
    }
}
