//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS2018WFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie
    {
        public int time { get; set; }
        public Nullable<int> esempio { get; set; }
        public Nullable<double> esempio2 { get; set; }
        public Nullable<int> Passengers { get; set; }
        public Nullable<int> jewelry { get; set; }
    }
}
